import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Autogenerated from the docs/ folder structure — order controlled by each
// file's front-matter `sidebar_position`, category order by _category_.json.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
